export const BASE_URL: string = "https://api.tmdb.org/3"
export const IMAGE_PATH: string = "https://image.tmdb.org/t/p/original"
export const API_KEY: string = "d89209bd4c01a0cb397a98c0a7c6a75b"
export const MOVIE: string = "/movie"
export const MATCH_API_KEY: string = "?api_key="
export const POPULAR: string = "/popular"